config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllres: { sessions: 'users/sessions' }
  devise_scope :user do
    post '/users/guest_sign_in', to: 'users/sessions#guest_sign_in'
  end

  get "search" => "searches#search"
  # , controllers: {
  #   registrations: 'users/registrations'
  # }

  get root to: 'homes#top'

  get '/home/about' => 'homes#about',as: 'about'

 # post '/homes/guest_sign_in', to: 'homes#guest_sign_in'


  resources :movies, only: [:new, :index, :show, :edit, :create, :update, :destroy] do
    resource :favorites, only: [:create, :destroy]
  end


  resources :users, only: [:index, :show, :edit, :update, :new, :create]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/favorite.rb
class Favorite < ApplicationRecord

  belongs_to :user
  #belongs_to :post_image

end

app/models/movie.rb
class Movie < ApplicationRecord
  belongs_to :user

   validates :title,presence: true
   validates :body,presence: true, length: { maximum: 200}

  has_many :favorites, dependent: :destroy

def self.looks(search, word)
    if search == "perfect_match"
      @movie = Movie.where("title LIKE?","#{word}")
    elsif search == "forward_match"
      @movie = Movie.where("title LIKE?","#{word}%")
    elsif search == "backward_match"
      @movie = Movie.where("title LIKE?","%#{word}")
    elsif search == "partial_match"
      @movie = Movie.where("title LIKE?","%#{word}%")
    else
      @movie = Movie.all
    end
end

  def favorited_by?(user)
    favorites.exists?(user_id: user.id)
  end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

   validates :name, uniqueness: true, length: { minimum: 2, maximum: 20}
   validates :introduction,length: { maximum: 50}

  has_many :favorites, dependent: :destroy
  has_many :movies, dependent: :destroy


  has_one_attached :profile_image

def self.looks(search, word)
    if search == "perfect_match"
      @user = User.where("name LIKE?", "#{word}")
    elsif search == "forward_match"
      @user = User.where("name LIKE?","#{word}%")
    elsif search == "backward_match"
      @user = User.where("name LIKE?","%#{word}")
    elsif search == "partial_match"
      @user = User.where("name LIKE?","%#{word}%")
    else
      @user = User.all
    end
end

  def get_profile_image(width, height)
  unless profile_image.attached?
    file_path = Rails.root.join('app/assets/images/no_image.jpg')
    profile_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
  end
  profile_image.variant(resize_to_limit: [width, height]).processed
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!, except: [:top, :about]
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :configure_permitted_parameters_sign_in, if: :devise_controller?


  def after_sign_in_path_for(resource)
    flash[:notice] = "Signed in successfully."
    user_path(current_user)
  end

  def after_sign_out_path_for(resource)
    flash[:notice] = "Signed out successfully."
    root_path
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:email])
  end

  def configure_permitted_parameters_sign_in
     devise_parameter_sanitizer.permit(:sign_in, keys: [:name])
  end

end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController

  def create
    #post_image = PostImage.find(params[:post_image_id])
    #favorite = current_user.favorites.new(post_image_id: post_image.id)
    #favorite.save
    #redirect_to post_image_path(post_image)
    @movie = Movie.find(params[:movie_id])
    favorite = Favorite.new(user_id: current_user.id, movie_id: @movie.id)
    favorite.save!

    redirect_to request.referer
  end

  def destroy
    #post_image = PostImage.find(params[:post_image_id])
    #favorite = current_user.favorites.find_by(post_image_id: post_image_id)
    #favorite.destroy
    #redirect_to post_image_path(post_image)
    @movie = Movie.find(params[:movie_id])
    favorite = Favorite.find_by(user_id: current_user.id, movie_id: @movie.id)
    favorite.destroy!

    redirect_to request.referer
  end

end

app/controllers/homes_controller.rb
class HomesController < ApplicationController

  def top
  end

  def about
  end
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController

   def create
    @movie = Movie.new(movie_params)
    @movies = Movie.all
    @movie.user_id = current_user.id
    @user = current_user
   if @movie.save
    flash[:notice] = "You have created book successfully."
    redirect_to movie_path(@movie.id)
   else
    render :index
   end
   end

  def index
    @movie = Movie.new
    @movies = Movie.all
    @user = current_user
  end


  def show
    @new_movie = Movie.new
    @movie = Movie.find(params[:id])
    @user = @movie.user
  end

  def edit
    @movie = Movie.find(params[:id])
    if @movie.user == current_user
      render "edit"
    else
      redirect_to movies_path
    end
  end

  def update
    @movie = Movie.find(params[:id])
    if @movie.update(movie_params)
    flash[:notice] = "You have updated book successfully."
    redirect_to movie_path(params[:id])
    else
      render :edit
    end
  end

  def destroy
    @movies = Movie.find(params[:id])
    @movies.destroy
    redirect_to movies_path
  end

  private

  def movie_params
    params.require(:movie).permit(:title, :body)
  end
end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController
  before_action :authenticate_user!

  def search
    @range = params[:range]

    if @range == "User"
      @users = User.looks(params[:search], params[:word])
    else
      @movies = Movie.looks(params[:search], params[:word])
    end
  end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  def guest_sign_in
    user = User.find_or_create_by(email: 'guest@example.com') do |user|
      user.password = SecureRandom.urlsafe_base64
      user.password_confirmation = user.password
      user.name = "guest"
    end
    sign_in user
    redirect_to root_path, notice: 'ゲストユーザーとしてログインしました。'
  end

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def create
    @book = Book.new(book_params)
    @books = Book.all
    @book.user_id = current_user.id
    @user = current_user
   if @book.save
    flash[:notice] = "You have created book successfully."
    redirect_to book_path(@book.id)
   else
    render :index
   end

  end

  def index
    @book = Book.new
    @books = Book.all
    @user = current_user
    @users = User.all
  end


  def show
    @book = Book.new
    @user = User.find(params[:id])
    @books = @user.books
  end

  def edit
    @user = User.find(params[:id])
    if @user != current_user
      redirect_to user_path(current_user)
    end
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
    flash[:notice] = "You have updated book successfully."
    redirect_to user_path(@user.id)
    else
      render :edit
    end
  end

  def destroy
    @books = Book.find(params[:id])
    @books.destroy
    redirect_to books_path
  end

  private

  def user_params
    params.require(:user).permit(:name, :introduction, :profile_image)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/_book.html.erb
 <div class ="col-md-3">
  <h2>User info</h2>
    <%= image_tag user.get_profile_image(100,100) %>
    <table class = "table">
     <tbody>
      <tr></tr>
      <tr>
       <th>name</th>
       <th><%= user.name %></th>
      </tr>

      <tr>
       <th>introduction</th>
       <th><%= user.introduction %></th>
      </tr>
     </tbody>
    </table>

    <div class= "low">
     <%= link_to edit_user_path(user), class: "btn btn-outline-secondary btn-block " do %>
      <i class="fas fa-user-cog"></i>
     <% end %>
     </div>

    <h2 class = "mt-3">New book</h2>
     <%= form_with model: book do |f| %>
      <div class = "form-group">
      <label for = "book_title">Title</label>
      <%= f.text_field :title, class: "form-control book_title" %>
      </div>

	     <div class = "form-group">
      <label for = "book_opinion">Opinion</label>
       <%= f.text_area :body, class: "form-control book_body" %>
      </div>

      <div class = "form-group">
       <%= f.submit 'Create Book', class: "btn btn-success" %>
      </div>
     <% end %>
 </div>

app/views/books/index.html.erb
<p id="notice"></p>
<div class = "container px-5 px-sm-0">
  <% if @book.errors.any? %>
   <div id = "error_explantion">
    <h3><%= pluralize(@book.errors.count, "error") %> prohibited this obj from being saved:</h3>
     <ul>
      <% @book.errors.full_messages.each do |message| %>
      <li><%= message %></li>
      <% end %>
     </ul>
   </div>
  <% end %>

  <div class = "row">
   <%= render 'books/book', user: @user, book: @book %>
     <div class = "col-md-8 offset-md-1">
      <h2>Books</h2>
      <table class="table table-hover table-inverse">
       <thead>
        <tr>
          <th></th>
          <th>Title</th>
          <th>Opinion</th>
          <th colspan="3"></th>
        </tr>
       </thead>

      <tbody>
       <% @books.each do |book| %>
        <tr>
         <td>
          <%= link_to (book.user) do %>
          <%= image_tag book.user.get_profile_image(100,100) %>
       <% end %>
         </td>
         <td><%=link_to book.title, book_path(book) %></td>
         <td><%= book.body %></td>
        </tr>
       <% end %>
      </tbody>
      </table>
     </div>
 </div>
</div>

app/views/homes/about.html.erb
<div class="container">
  <div class="row">
    <h1 class="px-3 mx-auto">
      Welcome to
      <i class="fas fa-movie"></i><strong>ReviewMovies</strong>!
    </h1>
  </div>
</div>

app/views/homes/top.html.erb
<div class="container">
  <div class="row">
    <div class="mx-auto col-11 col-sm-10 col-lg-8 col-xl-6">
      <h1>welcome to
      <i class="fas fa-book"></i><strong>ReviewMovies</strong> 
      </h1>
      <p>In <i class="fas fa-book"></i><strong>ReviewMovies</strong>,
      </p>
      <p>you can share and exchange  your opinions , inpressions , and emotions</p>
      <p> about various movies!</p>
      <div class="btn-wrapper col-10 mx-auto">
        <div class="row">
          <a class="btn btn-info btn-sm btn-block mb-3 sign_in" href="/users/sign_in">Log in</a>
        </div>
        <div class="row">
          <a class="btn btn-success btn-sm btn-block sign_up" href="/users/sign_up">Sign up</a>
        </div>
        <%= link_to 'ゲストログイン（閲覧用）', users_guest_sign_in_path, method: :post %>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ReviewMovie</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

   <header>
    <nav class = "navbar navbar-expand-lg navbar-dark bg-dark">
     <div class = "container">
      <a class = "navbar-brand" href = "/">
       <span>ReviewMovie</span>
      </a>


     <button class="navbar-toggler collapsed" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
       <span class="navbar-toggler-icon"></span>
     </button>

      <div class = "collapse navbar-collapse" id = "navbarNavDropdown" style>
       <ul class = "navbar-nav ml-auto">

        <% if user_signed_in? %>
         <li>
          <%= render 'searches/search' %>
         </li>
         <li><%= link_to user_path(current_user), class: 'nav-link text-light' do %>
             <i class="fas fa-home"></i> Home
             <% end %></li>

         <li><%= link_to  users_path, class: 'nav-link text-light' do %>
             <i class="fas fa-users"></i> Users
            <% end %></li>

         <li><%= link_to movies_path, class: 'nav-link text-light' do %>
            <i class="fas fa-book-open"></i> Movies
            <% end %></li>

         <li> <%= link_to destroy_user_session_path, method: :delete, class: 'nav-link text-light' do %>
             <i class="fas fa-sign-out-alt"></i> Log out
            <% end %></li>

        <% else %>

         <li><%= link_to '/', class: 'nav-link text-light' do %>
              <i class="fas fa-home"></i> Home
             <% end %></li>

         <li><%= link_to '/home/about', class: 'nav-link text-light' do %>
              <i class="fas fa-link"></i> About
             <% end %></li>

         <li><%= link_to new_user_registration_path, class: 'nav-link text-light' do %>
              <i class="fas fa-user-plus"></i> Sign up
             <% end %></li>

         <li><%= link_to new_user_session_path, class: 'nav-link text-light' do %>
              <i class="fas fa-sign-in-alt"></i> Log in
             <% end %></li>

        <% end %>

       </ul>
      </div>
     </div>
    </nav>
   </header>
  <%= flash[:notice] %>

  <%= yield %>

  <footer>
    <div class="container mt-5">
      <div class="row">
        <div class="mx-auto">
          <p>CopyRight Infratop.inc</p>
        </div>
      </div>
    </div>
  </footer>


 </body>
</html>

app/views/movies/_movie.html.erb
 <div class ="col-md-3">
  <h2>User info</h2>
    <%= image_tag user.get_profile_image(100,100) %>
    <table class = "table">
     <tbody>
      <tr></tr>
      <tr>
       <th>name</th>
       <th><%= user.name %></th>
      </tr>

      <tr>
       <th>introduction</th>
       <th><%= user.introduction %></th>
      </tr>
     </tbody>
    </table>

    <div class= "low">
     <%= link_to edit_user_path(user), class: "btn btn-outline-secondary btn-block " do %>
      <i class="fas fa-user-cog"></i>
     <% end %>
     </div>

    <h2 class = "mt-3">New movie</h2>
     <%= form_with model: movie do |f| %>
      <div class = "form-group">
      <label for = "movie_title">Title</label>
      <%= f.text_field :title, class: "form-control movie_title" %>
      </div>

	     <div class = "form-group">
      <label for = "movie_opinion">Opinion</label>
       <%= f.text_area :body, class: "form-control movie_body" %>
      </div>

      <div class = "form-group">
       <%= f.submit 'Create Movie', class: "btn btn-success" %>
      </div>
     <% end %>
 </div>

app/views/movies/edit.html.erb
<p id="notice"></p>
<div class = "container px-5 px-sm-0">
 <div class = "row">

   <div class = "col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
     <h1>Editing Movie</h1>

     <% if @movie.errors.any? %>
      <div id = "error_explantion">
      <h3><%= pluralize(@movie.errors.count, "error") %> prohibited this obj from being saved:</h3>
       <ul>
        <% @movie.errors.full_messages.each do |message| %>
        <li><%= message %></li>
        <% end %>
       </ul>
      </div>
    <% end %>
     <%= form_with model: @movie,url: movie_path(@movie), method: :patch do |f| %>
      <div class = "form-group">
       <label for="movie_title">Title</label>
       <%= f.text_field :title, class: "form-control movie_title" %>
      </div>

      <div class = "form-group">
       <label for="movie_opinion">Opinion</label>
       <%= f.text_area :body, class: "form-control movie_body" %>
      </div>

      <div class = "form-group">
       <%= f.submit 'Update Movie', class: "btn btn-success" %>
      </div>
     <% end %>
     <%= link_to 'Show',movie_path(@movie) %>|
     <%= link_to 'Back',movies_path %>

   </div>
 </div>
</div>

app/views/movies/index.html.erb
<p id="notice"></p>
<div class = "container px-5 px-sm-0">
  <% if @movie.errors.any? %>
   <div id = "error_explantion">
    <h3><%= pluralize(@movie.errors.count, "error") %> prohibited this obj from being saved:</h3>
     <ul>
      <% @movie.errors.full_messages.each do |message| %>
      <li><%= message %></li>
      <% end %>
     </ul>
   </div>
  <% end %>

  <div class = "row">
   <%= render 'movies/movie', user: @user, movie: @movie %>
     <div class = "col-md-8 offset-md-1">
      <h2>Movies</h2>
      <table class="table table-hover table-inverse">
       <thead>
        <tr>
          <th></th>
          <th>Title</th>
          <th>Opinion</th>
          <th colspan="3"></th>
        </tr>
       </thead>

      <tbody>
       <% @movies.each do |movie| %>
        <tr>
         <td>
          <%= link_to (movie.user) do %>
          <%= image_tag movie.user.get_profile_image(100,100) %>
       <% end %>
         </td>
         <td><%=link_to movie.title, movie_path(movie) %></td>
         <td><%= movie.body %></td>
        </tr>
       <% end %>
      </tbody>
      </table>
     </div>
 </div>
</div>

app/views/movies/new.html.erb
<h1>Movies#new</h1>
<p>Find me in app/views/movies/new.html.erb</p>

app/views/movies/show.html.erb
<p><% flash.each do |key, value| %>
    <%= content_tag(:id, value, class: "#{key}") %>
   <% end %></p>

<div class = "container px-5 px-sm-0">
 <div class = "row">
  <%= render 'movies/movie', user: @user, movie: @new_movie %>
  <div class = "col-md-8 offset-md-1">
   <h2>Movie detail</h2>
   <table class= "table" >
    <tbody>
     <tr>
      <td>
       <%= link_to user_path(@movie.user) do %>
        <%= image_tag @movie.user.get_profile_image(100,100) %></br>
        <%= @movie.user.name %>
       <% end %>
      </td>

      <td>
       <%=link_to @movie.title, movie_path(@movie) %>
      </td>

      <td>
       <%= @movie.body %>
      </td>
      <% if @movie.user == current_user %>
       <td>
        <%= link_to 'Edit', edit_movie_path(@movie) , class: "btn btn-sm btn-success edit_movie_39793" %>
       </td>
       <td>
        <%=link_to 'Destroy',movie_path(@movie),method: :delete, class: "btn btn-sm btn-danger destroy_movie_39800", "data-confirm" => "本当に消しますか？" %>
       </td>
      <% end %>
      <td>
       <% if @movie.favorited_by?(current_user) %>
      <%= link_to movie_favorites_path(@movie), method: :delete do %>
        ♥<%= @movie.favorites.count %> いいね
      <% end %>
    <% else %>
      <%= link_to movie_favorites_path(@movie), method: :post do %>
        ♡<%= @movie.favorites.count %> いいね
      <% end %>
      </td>
  <% end %>
     </tr>
    </tbody>
   </table>
  </div>
 </div>
</div>

app/views/searches/_search.html.erb
<% if user_signed_in? %>
  <div class="search_form">
    <%= form_with url: search_path, local: true, method: :get do |f| %>
      <%= f.text_field :word %>
      <%= f.select :range, options_for_select([['User'], ['Book']]) %>
      <%= f.select :search, options_for_select([["完全一致","perfect_match"], ["前方一致","forward_match"],  ["後方一致","backward_match"], ["部分一致","partial_match"]]) %>
      <%= f.submit "検索", class: "btn btn-primary" %>
    <% end %>
  </div>
<% end %>

app/views/searches/search.html.erb
<h2>Results index</h2>

<table class="table table-hover table-inverse">
  <% if @range == "User" %>
    <tbody>
      <% @users.each do |user| %>
        <tr>
          <td><%= user.name %></td>
        </tr>
      <% end %>
    </tbody>
  <% else %>
    <tbody>
      <% @movies.each do |movie| %>
        <tr>
          <td><%= movie.title %></td>
          <td><%= movie.body %></td>
        </tr>
      <% end %>
    </tbody>
  <% end %>
</table>

app/views/users/edit.html.erb
<div class="container">
 <div class="row">
  <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
   <h2>User info</h2>

<%= form_with model: @user do |f| %>

       <div class="error_explanation">
        <% if @user.errors.any? %>
         <h3><%= @user.errors.count %> errors prohibited this obj from being saved:</h3>
        <ul>
        <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
        <% end %>
        </ul>
        <% end %>
      </div>


    <div class="form-group">
     <label for="user_name">Name</label>
     <%= f.text_field :name, autofocus: true, id:"user_name", placeholder:"名前", class: "form-control name" %>
    </div>
    <div class="form-group">
     <label for="user_image">Image</label>
     <%= f.file_field :profile_image, id:"user_profile_image", accept: "image/*", class: "form-control-file user_image" %>
    </div>
     <div class="form-group">
      <label for="user_introduction">Introduction</label>
      <%= f.text_area :introduction, id:"user_introduction", class: "form-control introduction" %>
    </div>
     <div class="form-group">
       <%= f.submit "Update User", class: "btn btn-secondary" %>
     </div>
 <% end %>

   </div>
  </div>
 </div>

app/views/users/index.html.erb
<div class="container px-5 px-sm-0">
  <div class="row">

<%= render 'movies/movie',movie: @movie, user: @user %>

<div class="col-md-8 offset-md-1">
   <h2>Users</h2>
  <table class="table">
    <thead>
      <tr>
        <th>image</th>
        <th>name</th>
        <th colsapn="3"></th>
      </tr>
    </thead>
    <tbody>
      <% @users.each do |user| %>
      <tr>
        <td><%= image_tag user.get_profile_image(80,80) %></td>
        <td><%= user.name %></td>
        <td>
          <%= link_to "Show",user_path(user.id) %>
        </td>
      </tr>
          <% end %>
    </tbody>
   </table>
  </div>
 </div>
</div>

app/views/users/show.html.erb
<div class="container px-5 px-sm-0">
 <div class="row">

<%= render 'movies/movie', movie: @movie, user: @user %>

<div class="col-md-8 offset-md-1">
   <h2>Movies</h2>
  <table class="table table-hover table-inverse">
    <thead>
      <tr>
        <th></th>
        <th>Title</th>
        <th>Opinion</th>
        <th colsapn="3"></th>
      </tr>
    </thead>
    <tbody>
      <% @movies.each do |movie| %>
      <tr>
        <td>
          <%= link_to user_path(@user.id) do %>
          <%= image_tag movie.user.get_profile_image(80,80) %>
          <% end %>
        </td>
        <td>
          <%= link_to movie_path(movie.id) do %>
          <%= movie.title %>
          <% end %>
        </td>
        <td><%= movie.body %></td>
      </tr>
          <% end %>
    </tbody>
  </table>
  </div>
 </div>
</div>